# Generated by Django 6.0.5 on 2026-06-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='address',
            field=models.CharField(default='Pune', max_length=100),
        ),
    ]
