# Generated by Django 6.0.5 on 2026-06-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
